### ISSUE TITLE
Писане на commit message-и

### ISSUE THREAD

**Issue by meftim0va** [nkvelkov/OOP2015#1]
Здравей,

Това не е issue, а препоръка. В Git документацията пише, че е прието да се използва императивен език, т.е. заповедни изречения – все едно си Дейвид Ковърдейл и искаш да пиеш вулканична минерална вода от остров Фиджи.

<hr>

Source: 
- It’s also a good idea to use the imperative present tense in these messages. In other words, use commands. Instead of “I added tests for” or “Adding tests for,” use “Add tests for.” 
  http://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines
- Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
  or "Fixes bug."  This convention matches up with commit messages generated
  by commands like git merge and git revert.
  http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by nkvelkov** [comment]
Добре, мерси за препоръката! :)
